apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: acctdev
spec:
  ###################################################################
  ##  General Information about PostgreSQL
  ###################################################################
  # crunchy-postgres:ubi8-13.5-0
  # crunchy-postgres:ubi8-13.6-0
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.4-0
  openshift: false
  port: 5432
  postgresVersion: 14
  service:
    type: LoadBalancer
  instances:
    - name: 'pgc'
      replicas: 2 
      #resources:
      #  limits:
      #    cpu: 1.0
      #    memory: 2Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 2Gi

  ###################################################################
  ##  Backups
  ###################################################################
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-2
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * 0"
          incremental: "0 1 * * 1-6"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 2Gi

  ###################################################################
  ##  Crunchy Collect Sidecar (Monitoring)
  ###################################################################
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.1.1-0

  ###################################################################
  ##  PostgreSQL Configuration
  ###################################################################
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_parallel_workers: 2
          max_worker_processes: 2
          shared_buffers: 256MB
          work_mem: 2MB
