apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: keycloakdb
  namespace: keycloak
spec:
  ###################################################################
  ##  General Information about PostgreSQL
  ###################################################################
  # crunchy-postgres:ubi8-13.5-0
  # crunchy-postgres:ubi8-13.6-0
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.4-0
  openshift: false
  port: 5432
  postgresVersion: 14
  instances:
    - name: 'pgc'
      replicas: 2
      #resources:
      #  limits:
      #    cpu: 1.0
      #    memory: 1Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi

  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-2
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi

  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.1.1-0

